// Runs only the Easy Switch test executable against synthetic files; no host Codex mutation.
const {chromium}=require('@playwright/test');const fs=require('node:fs');const path=require('node:path');const {spawn}=require('node:child_process');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
(async()=>{
 const root=path.resolve('artifacts/native-smoke-'+Date.now()),home=path.join(root,'home'),store=path.join(root,'store');fs.mkdirSync(path.join(home,'sessions'),{recursive:true});fs.mkdirSync(store);const id=randomUUID();
 fs.writeFileSync(path.join(home,'sessions','example.jsonl'),[JSON.stringify({type:'session_meta',payload:{id,cwd:home,model_provider:'openai'}}),JSON.stringify({type:'event_msg',payload:{type:'user_message',message:'合成会话 · 原生窗口验收'}}),JSON.stringify({type:'response_item',payload:{type:'message',role:'assistant',content:[{type:'output_text',text:'这是一条合成测试内容，不含真实会话。'}]}})].join('\n')+'\n');
 fs.writeFileSync(path.join(store,'settings.json'),JSON.stringify({codexHome:home,automaticUpdates:false,automaticDownload:false,theme:'light'}));
 for(const name of ['state_5.sqlite','state_6.sqlite']){const db=new DatabaseSync(path.join(home,name));db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY,title TEXT,cwd TEXT,model_provider TEXT,rollout_path TEXT,updated_at INTEGER,archived INTEGER)');db.prepare('INSERT INTO threads VALUES(?,?,?,?,?,?,?)').run(id,'合成会话 · 重复索引',home,'openai',path.join(home,'sessions','example.jsonl'),1000,0);db.close()}
 const exe=path.resolve('target/release/easy-switch.exe');const proc=spawn(exe,['--store',store],{env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=47846 --remote-debugging-address=127.0.0.1'},windowsHide:true,stdio:'ignore'});let browser;
 try{for(let n=0;n<80;n++){try{browser=await chromium.connectOverCDP('http://127.0.0.1:47846');break}catch{await new Promise(r=>setTimeout(r,250))}}assert.ok(browser,'Native WebView2 did not start');const page=browser.contexts()[0].pages()[0];await page.waitForSelector('h1');
 const invoke=(command,args={})=>page.evaluate(({command,args})=>window.__TAURI_INTERNALS__.invoke(command,args),{command,args});
 const initial=await invoke('bootstrap');assert.equal(initial.providers.length,1);assert.equal(initial.settings.codexHome,home);assert.equal(initial.migrationError,null);
 const p={...initial.providers[0],id:'synthetic',name:'合成供应商',mode:'Api',baseUrl:'https://example.com/v1',model:'test-model',imageCompatibility:true};
 await invoke('save_provider',{provider:p,key:'synthetic-secret-never-display'});const boot=await invoke('bootstrap');assert.equal(boot.providers.length,2);assert.ok(!JSON.stringify(boot).includes('synthetic-secret'));assert.ok(boot.providers[1].hasKey);assert.ok(!JSON.stringify(boot).includes('protectedKey'));
 assert.ok(!fs.readFileSync(path.join(store,'providers.json'),'utf8').includes('synthetic-secret'));const scan=await invoke('scan_sessions');assert.equal(scan.sessions.length,1);assert.equal(scan.warnings.length,0);const detail=await invoke('session_detail',{id});assert.equal(detail.messages.length,1);
 await page.reload();await page.waitForSelector('.provider-card');await page.screenshot({path:'artifacts/screenshots/native-providers.png',animations:'disabled'});await page.getByRole('button',{name:'会话',exact:true}).click();await page.getByRole('button',{name:/合成会话/}).click();await page.getByText('这是一条合成测试内容，不含真实会话。').waitFor();await page.screenshot({path:'artifacts/screenshots/native-session.png',animations:'disabled'});
 const exported=await invoke('export_sessions',{ids:[id],folder:path.join(root,'export')});assert.equal(exported[0].state,'passed');
 await invoke('delete_provider',{id:'synthetic'});assert.equal((await invoke('bootstrap')).providers.length,1);await invoke('save_scroll',{id,position:125});assert.equal((await invoke('bootstrap')).settings.scrollPositions[id],125);
 fs.writeFileSync('artifacts/native-result.json',JSON.stringify({status:'passed',checks:['embedded frontend','native IPC','isolated store','DPAPI persistence','secret redaction','session scan and preview','Markdown export','provider delete','scroll persistence'],realCodexTouched:false},null,2));console.log('Native smoke passed (9 checks); real Codex untouched.');
 }finally{if(browser)await browser.close();proc.kill();}
})().catch(e=>{console.error(e.message);process.exitCode=1});
