import {useState,useEffect,lazy,Suspense} from 'react';
import {Plug,MessageSquare,History,Settings2,ChevronRight,Sun,Moon,Monitor,AlertCircle,CheckCircle2,Loader2,X,Download,ArrowRight,Activity,RefreshCw,ArchiveRestore} from 'lucide-react';
import {call,events,preview} from './api';
import type {Bootstrap,Provider,Settings,Diagnostic,Operation,UpdateStatus} from './types';
import {Brand,IconButton,Modal,Empty,type Confirm} from './components';
import {Providers,ProviderEditor} from './Providers';
const Sessions=lazy(()=>import('./Sessions'));const SettingsPage=lazy(()=>import('./SettingsPage'));
type Page='providers'|'sessions'|'backups'|'settings';const pageNames={providers:'供应商',sessions:'会话',backups:'备份恢复',settings:'设置'};
export default function App(){
 const [visited,setVisited]=useState(false);
 const [data,setData]=useState<Bootstrap|null>(null),[page,setPage]=useState<Page>('providers'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState<{text:string;error:boolean}|null>(null),[editor,setEditor]=useState<Provider|null>(null),[confirm,setConfirm]=useState<Confirm|null>(null),[diagnosis,setDiagnosis]=useState<{name:string;rows:Diagnostic[]}|null>(null),[progress,setProgress]=useState<{stage:string;detail:string}|null>(null),[update,setUpdate]=useState<UpdateStatus>({state:'idle'}),[ops,setOps]=useState<Operation[]>([]);
 function notify(text:string,error=false){setNotice({text,error})}async function refresh(){const next=await call<Bootstrap>('bootstrap');setData(next);if(next.migrationError)notify('旧数据导入未完成：'+next.migrationError,true)}async function refreshOps(){setOps(await call<Operation[]>('list_operations'))}
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){notify(String(e),true)}finally{setBusy(false);setProgress(null)}}
 useEffect(()=>{refresh().catch(e=>notify(String(e),true)).finally(()=>setLoading(false));const disposers=[events<{stage:string;detail:string}>('operation-progress',setProgress),events<UpdateStatus>('update-status',setUpdate)];return()=>{disposers.forEach(p=>p.then(fn=>fn()))}},[]);
 useEffect(()=>{const theme=data?.settings.theme??'system';const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply)},[data?.settings.theme]);
 useEffect(()=>{if(page==='sessions')setVisited(true)},[page]);
 useEffect(()=>{if(page==='backups')refreshOps().catch(e=>notify(String(e),true))},[page]);
 const current=data?.providers.find(p=>p.id===data.settings.activeProviderId);const nav=[{id:'providers' as const,icon:Plug},{id:'sessions' as const,icon:MessageSquare},{id:'backups' as const,icon:History},{id:'settings' as const,icon:Settings2}];
 function switchTo(p:Provider){setConfirm({title:'切换到 '+p.name,text:'将正常退出 Codex，备份配置与会话，修复供应商关联，然后重新启动。正在生成的任务将被中断；请先保存工作。',action:'切换并重启',run:async()=>{const message=await call<string>('switch_provider',{id:p.id});await refresh();notify(message)}})}
 function diagnose(p:Provider,network:boolean){const action=async()=>setDiagnosis({name:p.name,rows:await call<Diagnostic[]>('doctor',{id:p.id,network})});if(network)setConfirm({title:'执行联网诊断',text:'最多发送 5 个合成请求，可能产生少量费用。不发送本地会话，也不执行返回的工具。',action:'开始诊断',run:action});else run(action)}
 async function theme(theme:Settings['theme']){if(!data)return;setData({...data,settings:{...data.settings,theme}});if(!preview)await run(async()=>{await call('save_settings',{settings:{...data.settings,theme}});await refresh()})}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><Brand/><div><strong>Easy Switch</strong></div></div><div className="workspace-label"><span>CODEX 工作空间</span><span className="local-dot"/></div><nav aria-label="主导航">{nav.map(({id,icon:Icon})=><button key={id} className={page===id?'nav-item active':'nav-item'} onClick={()=>setPage(id)}><Icon size={19}/><span>{pageNames[id]}</span>{page===id&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><span className="connection-mark"><Plug size={16}/></span><div><span>当前供应商</span><strong>{current?.name??'尚未切换'}</strong></div></div><div className="sidebar-footer"><span>v{data?.version??'…'}</span><div className="theme-buttons">{([{id:'light',icon:Sun,label:'浅色'},{id:'dark',icon:Moon,label:'深色'},{id:'system',icon:Monitor,label:'跟随系统'}] as const).map(({id,icon:Icon,label})=><button key={id} aria-label={label} title={label} aria-pressed={data?.settings.theme===id} disabled={busy} onClick={()=>theme(id)}><Icon size={14}/></button>)}</div></div></div></aside><main><header className="topbar"><div className="breadcrumb">工作空间 <ChevronRight size={14}/><span>{pageNames[page]}</span></div><div className="topbar-end">{preview&&<span className="demo-label">演示预览 · 合成数据</span>}</div></header>{notice&&<div className={'notice '+(notice.error?'error':'')} role={notice.error?'alert':'status'}>{notice.error?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{notice.text}</span><IconButton label="关闭提示" onClick={()=>setNotice(null)}><X size={16}/></IconButton></div>}{update.state==='ready'&&<div className="update-banner"><Download size={17}/><span>Easy Switch {update.version} 已下载，准备安装</span><button onClick={()=>setPage('settings')}>查看更新 <ArrowRight size={15}/></button></div>}
 {loading?<div className="loading"><Loader2 className="spin"/>读取本地配置…</div>:!data?<Empty title="无法读取本地配置" body="处理提示中的错误后重试。"><button onClick={()=>run(refresh)}>重试</button></Empty>:<Suspense fallback={<div className="loading"><Loader2 className="spin"/>加载界面…</div>}>
 <div hidden={page!=='providers'}><Providers providers={data.providers} current={data.settings.activeProviderId} busy={busy} onEdit={setEditor} onSwitch={switchTo} onDiagnose={diagnose} onDelete={p=>setConfirm({title:'删除供应商配置',text:`删除“${p.name}”只移除此配置，不删除 Codex 会话。`,action:'删除配置',danger:true,run:async()=>{await call('delete_provider',{id:p.id});await refresh()}})}/></div>
 <div hidden={page!=='sessions'}>{(visited||page==='sessions')&&<Sessions visible={page==='sessions'} settings={data.settings} current={current} busy={busy} run={run} notify={notify} confirm={setConfirm}/>}</div>
 {page==='backups'&&<section className="page"><div className="page-heading"><div><h1>备份恢复</h1></div><button onClick={()=>run(refreshOps)} disabled={busy}><RefreshCw size={16}/>刷新</button></div>{ops.length?<div className="operation-list">{ops.map(o=><div className="operation" key={o.id+(o.legacy?'old':'')}><span className="operation-icon"><History size={20}/></span><div><h3>{o.description}</h3><p>{o.id} · {o.fileCount} 个文件{o.legacy?' · 旧版备份':''}</p></div><span className={'operation-state '+(['Complete','Restored','RolledBack'].includes(o.state)?'':'warning')}>{({Complete:'已完成',Restored:'已恢复',RolledBack:'已回滚',Preparing:'准备中断',Applying:'提交中断'} as Record<string,string>)[o.state]??o.state}</span><button disabled={busy||o.state==='Restored'||o.state==='RolledBack'} onClick={()=>setConfirm({title:'恢复这次操作',text:'将正常退出 Codex，检查摘要，再恢复操作前的数据。检测到外部修改时停止恢复。',action:'检查并恢复',run:async()=>{notify(await call<string>('restore_operation',{id:o.id,legacy:o.legacy}));await Promise.all([refresh(),refreshOps()])}})}><ArchiveRestore size={15}/>恢复</button></div>)}</div>:<Empty title="还没有操作备份" body="切换供应商或整理会话时，备份会自动出现在这里。"/>}</section>}
 {page==='settings'&&<SettingsPage version={data.version} settings={data.settings} busy={busy} update={update} run={run} notify={notify} onSave={async settings=>{await call('save_settings',{settings});await refresh();notify('设置已保存')}} onCheck={()=>run(async()=>{const v=await call<UpdateStatus>('check_update');setUpdate(v);if(v.state==='available'&&data.settings.automaticDownload)setUpdate(await call<UpdateStatus>('download_update'))})} onDownload={()=>run(async()=>setUpdate(await call<UpdateStatus>('download_update')))} onInstall={()=>setConfirm({title:'安装更新并重启',text:'安装已校验签名的更新。会话写入或代理请求尚未结束时，会停止安装并保留当前版本。',action:'安装更新',run:async()=>{await call('install_update')}})}/>}</Suspense>}
 {busy&&<div className="operation-progress" role="status"><Loader2 className="spin" size={18}/><div><strong>{progress?.stage??'正在处理'}</strong><span>{progress?.detail??'请稍候，结果会显示在这里'}</span></div><button onClick={()=>call('cancel_operation')} disabled={progress?.stage==='提交与校验'}>取消</button></div>}</main>
 {editor&&data&&<ProviderEditor provider={editor} all={data.providers} onClose={()=>setEditor(null)} onSave={async(p,key)=>{await call('save_provider',{provider:p,key});await refresh();setEditor(null);notify('配置已保存；切换后才会应用。')}}/>}
 {confirm&&<Modal title={confirm.title} onClose={()=>{if(!busy)setConfirm(null)}}><p className="confirm-copy">{confirm.text}</p><div className="modal-footer"><button onClick={()=>setConfirm(null)} disabled={busy}>取消</button><button className={confirm.danger?'danger':'primary'} disabled={busy} onClick={()=>{const action=confirm.run;setConfirm(null);run(action)}}>{confirm.action}</button></div></Modal>}
 {diagnosis&&<Modal title={diagnosis.name+' · 诊断报告'} onClose={()=>setDiagnosis(null)}><div className="diagnostics">{diagnosis.rows.map((d,i)=><div key={i}><span className={'diagnostic-icon '+d.state}>{d.state==='passed'?<CheckCircle2 size={18}/>:d.state==='failed'?<AlertCircle size={18}/>:<Activity size={18}/>}</span><div><strong>{d.name}</strong><p>{d.detail}</p></div><small>{({passed:'通过',failed:'失败',warning:'注意',untested:'未测'})[d.state]}</small></div>)}</div><div className="modal-footer"><button className="primary" onClick={()=>setDiagnosis(null)}>完成</button></div></Modal>}</div>
}
